[2024-07-23T03:27:47.195+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk9 manual__2024-07-23T03:27:43.875307+00:00 [queued]>
[2024-07-23T03:27:47.201+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk9 manual__2024-07-23T03:27:43.875307+00:00 [queued]>
[2024-07-23T03:27:47.201+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:27:47.202+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-23T03:27:47.202+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:27:47.209+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk9> on 2024-07-23 03:27:43.875307+00:00
[2024-07-23T03:27:47.212+0000] {standard_task_runner.py:55} INFO - Started process 7200 to run task
[2024-07-23T03:27:47.214+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_dag_complexa', 'tsk9', 'manual__2024-07-23T03:27:43.875307+00:00', '--job-id', '1310', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_dag_complexa.py', '--cfg-path', '/tmp/tmpqinqbwu6']
[2024-07-23T03:27:47.214+0000] {standard_task_runner.py:83} INFO - Job 1310: Subtask tsk9
[2024-07-23T03:27:47.255+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_dag_complexa.tsk9 manual__2024-07-23T03:27:43.875307+00:00 [running]> on host 448a9c84d52e
[2024-07-23T03:27:47.296+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_dag_complexa
AIRFLOW_CTX_TASK_ID=tsk9
AIRFLOW_CTX_EXECUTION_DATE=2024-07-23T03:27:43.875307+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-23T03:27:43.875307+00:00
[2024-07-23T03:27:47.297+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-23T03:27:47.297+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 4']
[2024-07-23T03:27:47.303+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T03:27:47.304+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2024-07-23T03:27:47.311+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2024-07-23T03:27:47.314+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_dag_complexa, task_id=tsk9, execution_date=20240723T032743, start_date=20240723T032747, end_date=20240723T032747
[2024-07-23T03:27:47.321+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1310 for task tsk9 (Bash command failed. The command returned a non-zero exit code 4.; 7200)
[2024-07-23T03:27:47.358+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-23T03:27:47.369+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
