[2024-07-23T03:18:10.004+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-23T03:18:09.191182+00:00 [queued]>
[2024-07-23T03:18:10.010+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-23T03:18:09.191182+00:00 [queued]>
[2024-07-23T03:18:10.010+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:18:10.010+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-23T03:18:10.010+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:18:10.020+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-07-23 03:18:09.191182+00:00
[2024-07-23T03:18:10.023+0000] {standard_task_runner.py:55} INFO - Started process 6352 to run task
[2024-07-23T03:18:10.025+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_triggerule_allfailed', 'tsk1', 'manual__2024-07-23T03:18:09.191182+00:00', '--job-id', '1302', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_triggerule_allfailed.py', '--cfg-path', '/tmp/tmpq3uf_huu']
[2024-07-23T03:18:10.025+0000] {standard_task_runner.py:83} INFO - Job 1302: Subtask tsk1
[2024-07-23T03:18:10.064+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-23T03:18:09.191182+00:00 [running]> on host 448a9c84d52e
[2024-07-23T03:18:10.103+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_triggerule_allfailed
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-23T03:18:09.191182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-23T03:18:09.191182+00:00
[2024-07-23T03:18:10.104+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-23T03:18:10.105+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-23T03:18:10.110+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T03:18:10.112+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-23T03:18:10.170+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-23T03:18:10.175+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_triggerule_allfailed, task_id=tsk1, execution_date=20240723T031809, start_date=20240723T031810, end_date=20240723T031810
[2024-07-23T03:18:10.187+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1302 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 6352)
[2024-07-23T03:18:10.218+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-23T03:18:10.233+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
