[2024-07-23T03:29:32.347+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-23T03:29:14.144099+00:00 [queued]>
[2024-07-23T03:29:32.354+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-23T03:29:14.144099+00:00 [queued]>
[2024-07-23T03:29:32.355+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:29:32.355+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-23T03:29:32.355+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-23T03:29:32.364+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk6> on 2024-07-23 03:29:14.144099+00:00
[2024-07-23T03:29:32.366+0000] {standard_task_runner.py:55} INFO - Started process 7369 to run task
[2024-07-23T03:29:32.368+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_dag_complexa', 'tsk6', 'manual__2024-07-23T03:29:14.144099+00:00', '--job-id', '1316', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_dag_complexa.py', '--cfg-path', '/tmp/tmpesp475vz']
[2024-07-23T03:29:32.368+0000] {standard_task_runner.py:83} INFO - Job 1316: Subtask tsk6
[2024-07-23T03:29:32.404+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-23T03:29:14.144099+00:00 [running]> on host 448a9c84d52e
[2024-07-23T03:29:32.448+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_dag_complexa
AIRFLOW_CTX_TASK_ID=tsk6
AIRFLOW_CTX_EXECUTION_DATE=2024-07-23T03:29:14.144099+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-23T03:29:14.144099+00:00
[2024-07-23T03:29:32.449+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-23T03:29:32.449+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-23T03:29:32.454+0000] {subprocess.py:86} INFO - Output:
[2024-07-23T03:29:32.456+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-23T03:29:32.463+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-23T03:29:32.466+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_dag_complexa, task_id=tsk6, execution_date=20240723T032914, start_date=20240723T032932, end_date=20240723T032932
[2024-07-23T03:29:32.474+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1316 for task tsk6 (Bash command failed. The command returned a non-zero exit code 1.; 7369)
[2024-07-23T03:29:32.506+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-23T03:29:32.526+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
