[2024-07-27T02:00:07.466+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-27T01:00:00+00:00 [queued]>
[2024-07-27T02:00:07.483+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-27T01:00:00+00:00 [queued]>
[2024-07-27T02:00:07.486+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-27T02:00:07.486+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-27T02:00:07.488+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-27T02:00:07.501+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): 4-Bash> on 2024-07-27 01:00:00+00:00
[2024-07-27T02:00:07.506+0000] {standard_task_runner.py:55} INFO - Started process 74180 to run task
[2024-07-27T02:00:07.509+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_email_operator', '4-Bash', 'scheduled__2024-07-27T01:00:00+00:00', '--job-id', '1726', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_email_operator.py', '--cfg-path', '/tmp/tmpcyoi8rzf']
[2024-07-27T02:00:07.510+0000] {standard_task_runner.py:83} INFO - Job 1726: Subtask 4-Bash
[2024-07-27T02:00:07.561+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-27T01:00:00+00:00 [running]> on host 029011c5aea1
[2024-07-27T02:00:07.705+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caue.ausec@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_email_operator
AIRFLOW_CTX_TASK_ID=4-Bash
AIRFLOW_CTX_EXECUTION_DATE=2024-07-27T01:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-27T01:00:00+00:00
[2024-07-27T02:00:07.708+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-27T02:00:07.709+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-27T02:00:07.722+0000] {subprocess.py:86} INFO - Output:
[2024-07-27T02:00:07.727+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-27T02:00:07.740+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-27T02:00:07.750+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=exemplo_email_operator, task_id=4-Bash, execution_date=20240727T010000, start_date=20240727T020007, end_date=20240727T020007
[2024-07-27T02:00:07.763+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1726 for task 4-Bash (Bash command failed. The command returned a non-zero exit code 1.; 74180)
[2024-07-27T02:00:07.787+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-27T02:00:07.812+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
