[2024-07-25T02:16:18.852+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-25T02:16:16.826014+00:00 [queued]>
[2024-07-25T02:16:18.894+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-25T02:16:16.826014+00:00 [queued]>
[2024-07-25T02:16:18.903+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.905+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-25T02:16:18.906+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.923+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-07-25 02:16:16.826014+00:00
[2024-07-25T02:16:18.930+0000] {standard_task_runner.py:55} INFO - Started process 31157 to run task
[2024-07-25T02:16:18.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_triggerule_allfailed', 'tsk1', 'manual__2024-07-25T02:16:16.826014+00:00', '--job-id', '1375', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_triggerule_allfailed.py', '--cfg-path', '/tmp/tmpsgiy54d9']
[2024-07-25T02:16:18.949+0000] {standard_task_runner.py:83} INFO - Job 1375: Subtask tsk1
[2024-07-25T02:16:19.096+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_triggerule_allfailed.tsk1 manual__2024-07-25T02:16:16.826014+00:00 [running]> on host 448a9c84d52e
[2024-07-25T02:16:19.157+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_triggerule_allfailed
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T02:16:16.826014+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-25T02:16:16.826014+00:00
[2024-07-25T02:16:19.160+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-25T02:16:19.164+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-25T02:16:19.177+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T02:16:19.179+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-25T02:16:19.194+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-25T02:16:19.203+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_triggerule_allfailed, task_id=tsk1, execution_date=20240725T021616, start_date=20240725T021618, end_date=20240725T021619
[2024-07-25T02:16:19.224+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1375 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 31157)
[2024-07-25T02:16:19.265+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-25T02:16:19.282+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
