[2024-07-26T14:00:05.021+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-26T13:00:00+00:00 [queued]>
[2024-07-26T14:00:05.028+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-26T13:00:00+00:00 [queued]>
[2024-07-26T14:00:05.028+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T14:00:05.028+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-26T14:00:05.028+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T14:00:05.038+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): 4-Bash> on 2024-07-26 13:00:00+00:00
[2024-07-26T14:00:05.043+0000] {standard_task_runner.py:55} INFO - Started process 18365 to run task
[2024-07-26T14:00:05.046+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_email_operator', '4-Bash', 'scheduled__2024-07-26T13:00:00+00:00', '--job-id', '1614', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_email_operator.py', '--cfg-path', '/tmp/tmpknrmwa6w']
[2024-07-26T14:00:05.046+0000] {standard_task_runner.py:83} INFO - Job 1614: Subtask 4-Bash
[2024-07-26T14:00:05.087+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_email_operator.4-Bash scheduled__2024-07-26T13:00:00+00:00 [running]> on host 029011c5aea1
[2024-07-26T14:00:05.135+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caue.ausec@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_email_operator
AIRFLOW_CTX_TASK_ID=4-Bash
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-26T13:00:00+00:00
[2024-07-26T14:00:05.137+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-26T14:00:05.137+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-26T14:00:05.144+0000] {subprocess.py:86} INFO - Output:
[2024-07-26T14:00:05.145+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-26T14:00:05.156+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-26T14:00:05.181+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=exemplo_email_operator, task_id=4-Bash, execution_date=20240726T130000, start_date=20240726T140005, end_date=20240726T140005
[2024-07-26T14:00:05.233+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1614 for task 4-Bash (Bash command failed. The command returned a non-zero exit code 1.; 18365)
[2024-07-26T14:00:05.281+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-26T14:00:05.311+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
